title: Bounty Village
author: admin
email: info@bountyvillage.org
description: > # this means to ignore newlines until "twitter_username:"
  An organisation founded with a passion to create a safer and better internet space for Myanmar. 
  This crowdsourced security platform creates a meet-up place for the companies with the hacker community to surface and tackle the vulnerabilities together.

# social links
twitter_username: bountyvillage
facebook_username: bountyvillage
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

gems:
  - jekyll-srcset

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
